### PR TITLE
Opaleye is now public

### PR DESCRIPTION
**Pull request by tomjaguarpaw**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Any chance you could regenerate your blog to get this in?

**Comment by ocharles** [comment]
Hey Tom. Unfortunately I have to mildly reformat a bunch of blog posts before I can do that, but I've made a note to try and do this some time soon - it's long overdue.

**Comment by tomjaguarpaw** [comment]
OK, thanks!

**Comment by ocharles** [comment]
Finally deployed

**Comment by tomjaguarpaw** [comment]
Nice, thanks!

**Pull request merged**
