### PR TITLE
Update 2014-12-09-recursive-do.lhs

### PR DESCRIPTION
**Pull request by vaibhavsagar**
Replace `largest` with `smallest` in `impureMin`.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
ping?

**Comment by ocharles** [comment]
Sorry dude, still trying to work out what I actually meant in this blog post! It seems to half be Mon, half be max!

**Comment by vaibhavsagar** [comment]
Alright, let me know if you want me to make any changes to this PR :smiley:.

**Comment by ocharles** [comment]
No worries, thanks for raising this.

**Comment by ocharles** [comment]
Classic 2 year delay to merge a one line change. Thank you though!

**Pull request merged**
